sudo: required
language: csharp
mono: none
dist: xenial
dotnet: 2.2

env:
  - FAKE_DETAILED_ERRORS=true

services:
  - docker

jobs:
  include:
    # daily
    - stage: build daily images
      script: ./fake.sh build -t daily
