AspNetCoreVersion = "8.0.0-preview.4.23260.4"
AspNetImage = "mcr.microsoft.com/dotnet/nightly/aspnet:8.0.0-preview.4"
SdkVersion = "8.0.100-preview.4.23260.5"
SdkImage = "mcr.microsoft.com/dotnet/nightly/sdk:8.0.100-preview.4"
RuntimeVersion = "8.0.0-preview.4.23259.5"
FetchTime = "2023-05-17T17:03:55.8708929+00:00"
