AspNetCoreVersion = "8.0.0-preview.7.23375.9"
AspNetImage = "mcr.microsoft.com/dotnet/nightly/aspnet:8.0.0-preview.7"
SdkVersion = "8.0.100-preview.7.23376.3"
SdkImage = "mcr.microsoft.com/dotnet/nightly/sdk:8.0.100-preview.7"
RuntimeVersion = "8.0.0-preview.7.23375.6"
FetchTime = "2023-08-10T17:03:41.1682661+00:00"
