AspNetCoreVersion = "8.0.1"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:8.0.1"
SdkVersion = "8.0.101"
SdkImage = "mcr.microsoft.com/dotnet/sdk:8.0.101"
RuntimeVersion = "8.0.1"
FetchTime = "2024-01-10T17:06:28.0747006+00:00"
