AspNetCoreVersion = "8.0.0-preview.6.23329.11"
AspNetImage = "mcr.microsoft.com/dotnet/nightly/aspnet:8.0.0-preview.6"
SdkVersion = "8.0.100-preview.6.23330.14"
SdkImage = "mcr.microsoft.com/dotnet/nightly/sdk:8.0.100-preview.6"
RuntimeVersion = "8.0.0-preview.6.23329.7"
FetchTime = "2023-07-12T17:05:44.2241766+00:00"
