AspNetCoreVersion = "8.0.3"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:8.0.3"
SdkVersion = "8.0.203"
SdkImage = "mcr.microsoft.com/dotnet/sdk:8.0.203"
RuntimeVersion = "8.0.3"
FetchTime = "2024-03-15T17:04:06.8655249+00:00"
