AspNetCoreVersion = "8.0.8"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:8.0.8"
SdkVersion = "8.0.401"
SdkImage = "mcr.microsoft.com/dotnet/sdk:8.0.401"
RuntimeVersion = "8.0.8"
FetchTime = "2024-08-16T17:07:06.1939513+00:00"
