AspNetCoreVersion = "8.0.2"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:8.0.2"
SdkVersion = "8.0.201"
SdkImage = "mcr.microsoft.com/dotnet/sdk:8.0.201"
RuntimeVersion = "8.0.2"
FetchTime = "2024-02-17T17:03:26.4839696+00:00"
