AspNetCoreVersion = "8.0.8"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:8.0.8"
SdkVersion = "8.0.400"
SdkImage = "mcr.microsoft.com/dotnet/sdk:8.0.400"
RuntimeVersion = "8.0.8"
FetchTime = "2024-08-13T17:07:14.4895257+00:00"
