AspNetCoreVersion = "8.0.4"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:8.0.4"
SdkVersion = "8.0.204"
SdkImage = "mcr.microsoft.com/dotnet/sdk:8.0.204"
RuntimeVersion = "8.0.4"
FetchTime = "2024-04-10T17:04:15.2365867+00:00"
