AspNetCoreVersion = "8.0.0"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:8.0.0"
SdkVersion = "8.0.100"
SdkImage = "mcr.microsoft.com/dotnet/sdk:8.0.100"
RuntimeVersion = "8.0.0"
FetchTime = "2023-11-15T17:05:44.0137987+00:00"
