AspNetCoreVersion = "8.0.8"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:8.0.8"
SdkVersion = "8.0.402"
SdkImage = "mcr.microsoft.com/dotnet/sdk:8.0.402"
RuntimeVersion = "8.0.8"
FetchTime = "2024-09-24T17:07:58.0687813+00:00"
