AspNetCoreVersion = "8.0.6"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:8.0.6"
SdkVersion = "8.0.302"
SdkImage = "mcr.microsoft.com/dotnet/sdk:8.0.302"
RuntimeVersion = "8.0.6"
FetchTime = "2024-06-11T17:07:28.0215502+00:00"
