AspNetCoreVersion = "8.0.3"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:8.0.3"
SdkVersion = "8.0.202"
SdkImage = "mcr.microsoft.com/dotnet/sdk:8.0.202"
RuntimeVersion = "8.0.3"
FetchTime = "2024-03-13T17:29:40.6545864+00:00"
