AspNetCoreVersion = "8.0.0-preview.5.23302.2"
AspNetImage = "mcr.microsoft.com/dotnet/nightly/aspnet:8.0.0-preview.5"
SdkVersion = "8.0.100-preview.5.23303.2"
SdkImage = "mcr.microsoft.com/dotnet/nightly/sdk:8.0.100-preview.5"
RuntimeVersion = "8.0.0-preview.5.23280.8"
FetchTime = "2023-06-13T17:04:55.3364965+00:00"
