AspNetCoreVersion = "8.0.5"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:8.0.5"
SdkVersion = "8.0.300"
SdkImage = "mcr.microsoft.com/dotnet/sdk:8.0.300"
RuntimeVersion = "8.0.5"
FetchTime = "2024-05-15T17:06:49.7811361+00:00"
