AspNetCoreVersion = "8.0.0-rc.2.23480.2"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:8.0.0-rc.2"
SdkVersion = "8.0.100-rc.2.23502.2"
SdkImage = "mcr.microsoft.com/dotnet/sdk:8.0.100-rc.2"
RuntimeVersion = "8.0.0-rc.2.23479.6"
FetchTime = "2023-10-11T17:04:41.6853927+00:00"
