AspNetCoreVersion = "8.0.2"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:8.0.2"
SdkVersion = "8.0.200"
SdkImage = "mcr.microsoft.com/dotnet/sdk:8.0.200"
RuntimeVersion = "8.0.2"
FetchTime = "2024-02-14T17:05:16.1656797+00:00"
