AspNetCoreVersion = "8.0.6"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:8.0.6"
SdkVersion = "8.0.301"
SdkImage = "mcr.microsoft.com/dotnet/sdk:8.0.301"
RuntimeVersion = "8.0.6"
FetchTime = "2024-06-01T17:04:14.3492484+00:00"
