AspNetCoreVersion = "8.0.0-preview.2.23153.2"
AspNetImage = "mcr.microsoft.com/dotnet/nightly/aspnet:8.0.0-preview.2"
SdkVersion = "8.0.100-preview.2.23157.25"
SdkImage = "mcr.microsoft.com/dotnet/nightly/sdk:8.0.100-preview.2"
RuntimeVersion = "8.0.0-preview.2.23128.3"
FetchTime = "2023-03-14T17:03:36.9141601+00:00"
