AspNetCoreVersion = "8.0.0-preview.1.23112.2"
AspNetImage = "mcr.microsoft.com/dotnet/nightly/aspnet:8.0.0-preview.1"
SdkVersion = "8.0.100-preview.1.23115.2"
SdkImage = "mcr.microsoft.com/dotnet/nightly/sdk:8.0.100-preview.1"
RuntimeVersion = "8.0.0-preview.1.23110.8"
FetchTime = "2023-03-13T04:30:16.1371031+00:00"
