AspNetCoreVersion = "8.0.7"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:8.0.7"
SdkVersion = "8.0.303"
SdkImage = "mcr.microsoft.com/dotnet/sdk:8.0.303"
RuntimeVersion = "8.0.7"
FetchTime = "2024-07-09T17:06:58.8587572+00:00"
