AspNetCoreVersion = "8.0.0-preview.3.23177.8"
AspNetImage = "mcr.microsoft.com/dotnet/nightly/aspnet:8.0.0-preview.3"
SdkVersion = "8.0.100-preview.3.23178.7"
SdkImage = "mcr.microsoft.com/dotnet/nightly/sdk:8.0.100-preview.3"
RuntimeVersion = "8.0.0-preview.3.23174.8"
FetchTime = "2023-04-12T17:04:18.3647530+00:00"
