AspNetCoreVersion = "7.0.12"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:7.0.12"
SdkVersion = "7.0.402"
SdkImage = "mcr.microsoft.com/dotnet/sdk:7.0.402"
RuntimeVersion = "7.0.12"
FetchTime = "2023-10-11T17:04:41.6408913+00:00"
