AspNetCoreVersion = "7.0.14"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:7.0.14"
SdkVersion = "7.0.404"
SdkImage = "mcr.microsoft.com/dotnet/sdk:7.0.404"
RuntimeVersion = "7.0.14"
FetchTime = "2023-11-15T17:05:43.3756811+00:00"
