AspNetCoreVersion = "7.0.7"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:7.0.7"
SdkVersion = "7.0.304"
SdkImage = "mcr.microsoft.com/dotnet/sdk:7.0.304"
RuntimeVersion = "7.0.7"
FetchTime = "2023-06-13T17:04:55.2713967+00:00"
