AspNetCoreVersion = "7.0.20"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:7.0.20"
SdkVersion = "7.0.410"
SdkImage = "mcr.microsoft.com/dotnet/sdk:7.0.410"
RuntimeVersion = "7.0.20"
FetchTime = "2024-07-09T17:06:58.0415949+00:00"
