AspNetCoreVersion = "7.0.19"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:7.0.19"
SdkVersion = "7.0.409"
SdkImage = "mcr.microsoft.com/dotnet/sdk:7.0.409"
RuntimeVersion = "7.0.19"
FetchTime = "2024-05-15T17:06:49.7400941+00:00"
