AspNetCoreVersion = "7.0.11"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:7.0.11"
SdkVersion = "7.0.401"
SdkImage = "mcr.microsoft.com/dotnet/sdk:7.0.401"
RuntimeVersion = "7.0.11"
FetchTime = "2023-09-13T17:04:08.0848128+00:00"
