AspNetCoreVersion = "7.0.20"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:7.0.20"
SdkVersion = "7.0.410"
SdkImage = "mcr.microsoft.com/dotnet/sdk:7.0.410"
RuntimeVersion = "7.0.20"
FetchTime = "2024-09-24T17:07:57.3290136+00:00"
