AspNetCoreVersion = "7.0.17"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:7.0.17"
SdkVersion = "7.0.407"
SdkImage = "mcr.microsoft.com/dotnet/sdk:7.0.407"
RuntimeVersion = "7.0.17"
FetchTime = "2024-03-13T17:29:39.9921933+00:00"
