AspNetCoreVersion = "7.0.11"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:7.0.11"
SdkVersion = "7.0.401"
SdkImage = "mcr.microsoft.com/dotnet/sdk:7.0.401"
RuntimeVersion = "7.0.11"
FetchTime = "2023-09-16T17:03:14.4342770+00:00"
