AspNetCoreVersion = "7.0.20"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:7.0.20"
SdkVersion = "7.0.410"
SdkImage = "mcr.microsoft.com/dotnet/sdk:7.0.410"
RuntimeVersion = "7.0.20"
FetchTime = "2024-06-01T17:04:13.8407426+00:00"
