AspNetCoreVersion = "7.0.9"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:7.0.9"
SdkVersion = "7.0.306"
SdkImage = "mcr.microsoft.com/dotnet/sdk:7.0.306"
RuntimeVersion = "7.0.9"
FetchTime = "2023-07-12T17:05:43.6880983+00:00"
