AspNetCoreVersion = "7.0.13"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:7.0.13"
SdkVersion = "7.0.403"
SdkImage = "mcr.microsoft.com/dotnet/sdk:7.0.403"
RuntimeVersion = "7.0.13"
FetchTime = "2023-10-25T17:03:26.6271174+00:00"
