AspNetCoreVersion = "7.0.8"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:7.0.8"
SdkVersion = "7.0.305"
SdkImage = "mcr.microsoft.com/dotnet/sdk:7.0.305"
RuntimeVersion = "7.0.8"
FetchTime = "2023-06-23T17:06:14.9894834+00:00"
