AspNetCoreVersion = "7.0.16"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:7.0.16"
SdkVersion = "7.0.406"
SdkImage = "mcr.microsoft.com/dotnet/sdk:7.0.406"
RuntimeVersion = "7.0.16"
FetchTime = "2024-02-17T17:03:25.8792506+00:00"
