AspNetCoreVersion = "7.0.15"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:7.0.15"
SdkVersion = "7.0.405"
SdkImage = "mcr.microsoft.com/dotnet/sdk:7.0.405"
RuntimeVersion = "7.0.15"
FetchTime = "2024-01-10T17:06:27.4493345+00:00"
