AspNetCoreVersion = "7.0.5"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:7.0.5"
SdkVersion = "7.0.203"
SdkImage = "mcr.microsoft.com/dotnet/sdk:7.0.203"
RuntimeVersion = "7.0.5"
FetchTime = "2023-04-12T17:04:17.8956880+00:00"
