AspNetCoreVersion = "7.0.10"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:7.0.10"
SdkVersion = "7.0.400"
SdkImage = "mcr.microsoft.com/dotnet/sdk:7.0.400"
RuntimeVersion = "7.0.10"
FetchTime = "2023-08-10T17:03:40.8050375+00:00"
