AspNetCoreVersion = "7.0.5"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:7.0.5"
SdkVersion = "7.0.302"
SdkImage = "mcr.microsoft.com/dotnet/sdk:7.0.302"
RuntimeVersion = "7.0.5"
FetchTime = "2023-05-17T17:03:55.6901380+00:00"
