AspNetCoreVersion = "7.0.4"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:7.0.4"
SdkVersion = "7.0.202"
SdkImage = "mcr.microsoft.com/dotnet/sdk:7.0.202"
RuntimeVersion = "7.0.4"
FetchTime = "2023-03-14T17:03:36.5001583+00:00"
