AspNetCoreVersion = "7.0.18"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:7.0.18"
SdkVersion = "7.0.408"
SdkImage = "mcr.microsoft.com/dotnet/sdk:7.0.408"
RuntimeVersion = "7.0.18"
FetchTime = "2024-04-10T17:04:14.5666584+00:00"
