AspNetCoreVersion = "5.0.17"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:5.0.17"
SdkVersion = "5.0.408"
SdkImage = "mcr.microsoft.com/dotnet/sdk:5.0.408"
RuntimeVersion = "5.0.17"
FetchTime = "2022-05-29T15:12:51.1550135+08:00"
