AspNetCoreVersion = "5.0.17"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:5.0.17"
SdkVersion = "5.0.408"
SdkImage = "mcr.microsoft.com/dotnet/sdk:5.0.408"
RuntimeVersion = "5.0.17"
FetchTime = "2022-10-12T17:32:49.2231733+00:00"
