FROM {{AspNetImage}}

# set up environment
ENV ASPNETCORE_URLS http://+:80

# set up node
ENV NODE_VERSION {{NodeVersion}}
ENV YARN_VERSION {{YarnVersion}}
ENV NODE_DOWNLOAD_SHA {{NodeSHA}}
ENV NODE_DOWNLOAD_URL https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz

RUN wget "$NODE_DOWNLOAD_URL" -O nodejs.tar.gz \
    && echo "$NODE_DOWNLOAD_SHA  nodejs.tar.gz" | sha256sum -c - \
    && tar -xzf "nodejs.tar.gz" -C /usr/local --strip-components=1 \
    && rm nodejs.tar.gz \
    && npm i -g yarn@$YARN_VERSION \
    && ln -s /usr/local/bin/node /usr/local/bin/nodejs

WORKDIR /
