AspNetCoreVersion = "6.0.16"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.16"
SdkVersion = "6.0.408"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.408"
RuntimeVersion = "6.0.16"
FetchTime = "2023-04-12T17:04:17.0894358+00:00"
