AspNetCoreVersion = "6.0.11"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.11"
SdkVersion = "6.0.403"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.403"
RuntimeVersion = "6.0.11"
FetchTime = "2022-11-09T17:05:50.3373820+00:00"
