AspNetCoreVersion = "6.0.29"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.29"
SdkVersion = "6.0.421"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.421"
RuntimeVersion = "6.0.29"
FetchTime = "2024-04-10T17:04:13.7109013+00:00"
