AspNetCoreVersion = "6.0.16"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.16"
SdkVersion = "6.0.408"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.408"
RuntimeVersion = "6.0.16"
FetchTime = "2023-05-17T17:03:55.3058698+00:00"
