AspNetCoreVersion = "6.0.6"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.6"
SdkVersion = "6.0.301"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.301"
RuntimeVersion = "6.0.6"
FetchTime = "2022-07-02T04:31:40.8070779+00:00"
