AspNetCoreVersion = "6.0.15"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.15"
SdkVersion = "6.0.407"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.407"
RuntimeVersion = "6.0.15"
FetchTime = "2023-03-15T17:01:33.3315253+00:00"
