AspNetCoreVersion = "6.0.22"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.22"
SdkVersion = "6.0.414"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.414"
RuntimeVersion = "6.0.22"
FetchTime = "2023-09-13T17:04:07.9626992+00:00"
