AspNetCoreVersion = "6.0.21"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.21"
SdkVersion = "6.0.413"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.413"
RuntimeVersion = "6.0.21"
FetchTime = "2023-08-10T17:03:40.2397002+00:00"
