AspNetCoreVersion = "6.0.32"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.32"
SdkVersion = "6.0.424"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.424"
RuntimeVersion = "6.0.32"
FetchTime = "2024-07-09T17:06:57.0548329+00:00"
