AspNetCoreVersion = "6.0.19"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.19"
SdkVersion = "6.0.411"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.411"
RuntimeVersion = "6.0.19"
FetchTime = "2023-06-23T17:06:14.4127447+00:00"
