AspNetCoreVersion = "6.0.12"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.12"
SdkVersion = "6.0.404"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.404"
RuntimeVersion = "6.0.12"
FetchTime = "2022-12-14T17:01:46.2886749+00:00"
