AspNetCoreVersion = "6.0.14"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.14"
SdkVersion = "6.0.406"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.406"
RuntimeVersion = "6.0.14"
FetchTime = "2023-02-15T17:01:20.8298121+00:00"
