AspNetCoreVersion = "6.0.26"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.26"
SdkVersion = "6.0.418"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.418"
RuntimeVersion = "6.0.26"
FetchTime = "2024-01-10T17:06:26.6483489+00:00"
