AspNetCoreVersion = "6.0.5"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.5"
SdkVersion = "6.0.300"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.300"
RuntimeVersion = "6.0.5"
FetchTime = "2022-05-29T09:04:52.0995101+00:00"
