AspNetCoreVersion = "6.0.33"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.33"
SdkVersion = "6.0.425"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.425"
RuntimeVersion = "6.0.33"
FetchTime = "2024-08-13T17:07:14.3104950+00:00"
