AspNetCoreVersion = "6.0.30"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.30"
SdkVersion = "6.0.422"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.422"
RuntimeVersion = "6.0.30"
FetchTime = "2024-05-15T17:06:49.6341192+00:00"
