AspNetCoreVersion = "6.0.7"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.7"
SdkVersion = "6.0.302"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.302"
RuntimeVersion = "6.0.7"
FetchTime = "2022-07-13T17:15:11.4455728+00:00"
