AspNetCoreVersion = "6.0.13"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.13"
SdkVersion = "6.0.405"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.405"
RuntimeVersion = "6.0.13"
FetchTime = "2023-01-11T17:04:26.2799175+00:00"
