AspNetCoreVersion = "6.0.10"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.10"
SdkVersion = "6.0.402"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.402"
RuntimeVersion = "6.0.10"
FetchTime = "2022-10-12T17:32:49.3431329+00:00"
