AspNetCoreVersion = "6.0.18"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.18"
SdkVersion = "6.0.410"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.410"
RuntimeVersion = "6.0.18"
FetchTime = "2023-06-13T17:04:55.1174538+00:00"
