AspNetCoreVersion = "6.0.28"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.28"
SdkVersion = "6.0.420"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.420"
RuntimeVersion = "6.0.28"
FetchTime = "2024-03-15T17:04:05.2581288+00:00"
