AspNetCoreVersion = "6.0.24"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.24"
SdkVersion = "6.0.416"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.416"
RuntimeVersion = "6.0.24"
FetchTime = "2023-10-25T17:03:26.0729224+00:00"
