AspNetCoreVersion = "6.0.20"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.20"
SdkVersion = "6.0.412"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.412"
RuntimeVersion = "6.0.20"
FetchTime = "2023-07-12T17:05:42.8072236+00:00"
