AspNetCoreVersion = "6.0.8"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.8"
SdkVersion = "6.0.400"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.400"
RuntimeVersion = "6.0.8"
FetchTime = "2022-08-09T17:12:04.3221482+00:00"
