AspNetCoreVersion = "6.0.27"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.27"
SdkVersion = "6.0.419"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.419"
RuntimeVersion = "6.0.27"
FetchTime = "2024-02-17T17:03:25.0297446+00:00"
