AspNetCoreVersion = "6.0.31"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.31"
SdkVersion = "6.0.423"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.423"
RuntimeVersion = "6.0.31"
FetchTime = "2024-06-11T17:07:26.6876913+00:00"
