AspNetCoreVersion = "6.0.25"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.25"
SdkVersion = "6.0.417"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.417"
RuntimeVersion = "6.0.25"
FetchTime = "2023-11-15T17:05:42.6373537+00:00"
