AspNetCoreVersion = "6.0.23"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.23"
SdkVersion = "6.0.415"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.415"
RuntimeVersion = "6.0.23"
FetchTime = "2023-10-11T17:04:41.4828906+00:00"
