AspNetCoreVersion = "6.0.9"
AspNetImage = "mcr.microsoft.com/dotnet/aspnet:6.0.9"
SdkVersion = "6.0.401"
SdkImage = "mcr.microsoft.com/dotnet/sdk:6.0.401"
RuntimeVersion = "6.0.9"
FetchTime = "2022-09-14T17:19:55.9459472+00:00"
